name: Deploy IR Engine

on:
  push:
    branches: [dev, int, stg]
    paths-ignore: 
      - '**/*.md'
      - '.*ignore'
  workflow_dispatch:
    inputs:
      environment:
        description: Evironment to Deploy
        required: true
        type: choice
        options: 
        - dev
        - int
        - stg

env:
  TARGET_BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  remote-dispatch-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send Remote Dispatch to Deploy IR-Engine
        run: |
          curl -H "Authorization: token ${{ secrets.IR_ORG_ACCESS_TOKEN }}" \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            ${{ secrets.IR_ENGINE_OPS_API_URL }} \
            -d '{"event_type": "deploy-ir-engine", "client_payload": {"environment": "${{ env.TARGET_BRANCH_NAME }}"}}'
      - name: Deploy Storybook
        run: |
          if [ "$TARGET_BRANCH_NAME" == "dev" ]; then
            echo "Changed files:"
            git diff --name-only ${{ github.event.before }} ${{ github.sha }}

            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q 'packages/ui/'; then
              echo "UI package changes detected."
              echo "Deploying storybook"
              curl -L \
                -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.STORYBOOK_DOCS_PAT }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/ir-engine/storybook-docs/dispatches \
                -d '{"event_type":"push"}'
            fi
          fi
